version: '3.1'

services:
  shipping_http: 
    image: node:16
    build: .
    environment:
      DATABASE_URL: postgresql://example:example@db:5432/mydb?schema=public
    depends_on:
      - "shipping_db"
  shipping_db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example